---
- name: Create AWS EC2 Key Pair
  hosts: localhost
  connection: local
  gather_facts: no

  vars_files:
    - pass.yml  # 여기에 aws_access_key, aws_secret_key가 들어있어야 함

  vars:
    key_name: project2-key
    region: ap-northeast-2
    pem_file_path: "./{{ key_name }}.pem"

  tasks:
    - name: Create EC2 Key Pair
      amazon.aws.ec2_key:
        name: "{{ key_name }}"
        state: present
        region: "{{ region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
      register: key_result

    - name: Save private key to PEM file (only if new key created)
      copy:
        content: "{{ key_result.key.private_key }}"
        dest: "{{ pem_file_path }}"
        mode: '0400'
      when: key_result.changed and (key_result.key.private_key is defined)

    - name: Delete EC2 Key Pair from AWS (optional, for cleanup/test)
      amazon.aws.ec2_key:
        name: "{{ key_name }}"
        region: "{{ region }}"
        state: absent
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
      when: false  # 필요하면 true로 변경하거나 이 태스크 삭제
