---
- name: Create EC2 Key Pair
  amazon.aws.ec2_key:
    name: "{{ key_name }}"
    state: present
    region: "{{ region }}"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
  register: key_result

- name: Save private key to PEM file (only if new key created)
  copy:
    content: "{{ key_result.key.private_key }}"
    dest: "{{ pem_file_path }}"
    mode: '0400'
  when: key_result.changed and (key_result.key.private_key is defined)
