---
# tasks file for s3
- name: Create S3 bucket
  s3_bucket:
    name: project2-bucket-00
    state: present
    region: "{{ region }}"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
