---
# Delete jenkins.domain.com
- name: Delete project2.jenkins.jinlabs.net record
  community.aws.route53:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    state: absent
    zone: jinlabs.net
    record: project2.jenkins.jinlabs.net
    type: A
    value: "{{ dns_name }}"
    alias: true
    alias_hosted_zone_id: "{{ hosted_zone_id }}"
    overwrite: true
  register: delete_domain_jenkins_result

# Delete web.domain.com
- name: Delete project2.jinlabs.net record
  community.aws.route53:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    state: absent
    zone: jinlabs.net
    record: project2.jinlabs.net
    type: A
    value: "{{ dns_name }}"
    alias: true
    alias_hosted_zone_id: "{{ hosted_zone_id }}"
    overwrite: true
  register: delete_domain_web_result
