---
- name: Delete EC2 Key Pair
  amazon.aws.ec2_key:
    name: "{{ key }}"
    state: absent
    region: "{{ region }}"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
